[project]
name = "llm"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "anthropic>=0.97.0",
    "langchain>=1.2.17",
    "langchain-anthropic>=1.4.2",
    "langchain-openai>=1.2.1",
    "openai>=2.33.0",
]


#[[tool.uv.index]]
#name = "aliyun"
#url = "https://mirrors.aliyun.com/pypi/simple"
